install:
- nvm install 10
- npm install -g "npm@$(jq -r '.engines.npm' package.json)"
- npm ci

matrix:
  include:
    - language: android
      jdk: oraclejdk8
      android:
        components:
          - build-tools-28.0.3
          - android-28
      before_install:
        - yes | sdkmanager "platforms;android-28"
        - yes | sdkmanager "build-tools;28.0.3"
        
      script:
        - "./android/gradlew assembleRelease -p android/"
        - npm test

        
      cache:
        directories:
          - node_modules

    - language: node_js
      node_js:
        - 12.13

      cache:
        directories:
          - node_modules

      before_install:
        - cd api
      install:
        - npm install
        - npm install jest supertest --save-dev
      script:
        - npm test